POST http://localhost:4004/odata/v4/pokemon/Trainers
Content-Type: application/json

{
    "FirstName": "AshMayusculas",
    "LastName": "KetchuMayus",
    "Email": "ASH@GMAIL.COM", 
    "Birthdate": "2020-10-20"
}

###
POST http://localhost:4004/odata/v4/pokemon/Trainers
Content-Type: application/json

{
    "ID": "00000000-0000-0000-0000-000000011111",
    "FirstName": "Special",
    "LastName": "Trainer",
    "Email": "SPECIALTRAINER@GMAIL.COM",
    "Birthdate": "2000-01-01",
    "teams": [
        {
            "Name": "The team of special trainers",
            "Description": "This is a very special team",
            "Active": true,
            "captures": [
                {
                    "PokemonName": "Squirtle",
                    "Weight": 20,
                    "Height": 20
                },
                {
                    "PokemonName": "Charizard",
                    "Weight": 40,
                    "Height": 40
                }
            ]
        }
    ]
}

###
GET http://localhost:4004/odata/v4/pokemon/Trainers

###
GET http://localhost:4004/odata/v4/pokemon/Trainers(00000000-0000-0000-0000-000000011111)?$expand=teams($expand=captures)

###
PATCH http://localhost:4004/odata/v4/pokemon/Trainers(00000000-0000-0000-0000-000000011111)?$expand=teams($expand=captures)
Content-Type: application/json

{
    "LastName": "Not Special",
    "Email": "notspecialTrainer@gmail.com"
}
 
###
DELETE http://localhost:4004/odata/v4/pokemon/Trainers(00000000-0000-0000-0000-000000011111)



### Two teams
POST http://localhost:4004/odata/v4/pokemon/Trainers
Content-Type: application/json

{
    "ID": "00000000-0000-0000-0000-000000111111",
    "FirstName": "Ash",
    "LastName": "Twoteams",
    "Email": "ashteams@gmail.com",
    "Birthdate": "2000-01-01",
    "teams": [
        {
            "Name": "First Team",
            "Description": "Water",
            "Active": true,
            "captures": [
                { "PokemonName": "Squirtle", "Weight": 50, "Height": 50 }
            ]
        },
        {
            "Name": "Second Team",
            "Description": "Fire",
            "Active": false,
            "captures": [
                { "PokemonName": "Charmander", "Weight": 40, "Height": 50 },
                { "PokemonName": "Charizard", "Weight": 40, "Height": 50 }
            ]
        }
    ]
}

###
GET http://localhost:4004/odata/v4/pokemon/Trainers(00000000-0000-0000-0000-000000111111)?$expand=teams($expand=captures)

###
POST http://localhost:4004/odata/v4/pokemon/Trainers
Content-Type: application/json

{
    "FirstName": "Trainer",
    "LastName": "WithMedal",
    "Email": "TrainerWithMedal@gmail.com",
    "Birthdate": "1999-01-01",
    "trainerMedals": [
        {
            "medal_ID": "22222222-2222-2222-2222-222222222222"
        }
    ]
}
