###
POST http://localhost:4004/odata/v4/pokemon/Teams
Content-Type: application/json

{
    "Name": "Example Team",
    "Description": "This is the example team 1",
    "Active": true
}

//The team is fc4f6e1a-1395-4072-a734-517cf2ca3737
###
GET http://localhost:4004/odata/v4/pokemon/Teams(fc4f6e1a-1395-4072-a734-517cf2ca3737)


//Set to inactive a team
###
DELETE http://localhost:4004/odata/v4/pokemon/Teams(fc4f6e1a-1395-4072-a734-517cf2ca3737)

//Check the inactive team 
###
GET http://localhost:4004/odata/v4/pokemon/Teams(fc4f6e1a-1395-4072-a734-517cf2ca3737)

### Make an empty team
POST http://localhost:4004/odata/v4/pokemon/Teams
Content-Type: application/json

{
    "Name": "Empty Test Team"
}

### Active the team and should fail 54-7f6c024ec8
POST http://localhost:4004/odata/v4/pokemon/Teams(8c600f34-6b7a-4ee1-96dc)/setTeamStatus
Content-Type: application/json

{
    "Active": false
}
### 
POST http://localhost:4004/odata/v4/pokemon/Teams(124e12d4-d04b-4f19-a26d-ae7c3ec96b16)/setTeamStatus
Content-Type: application/json

{
    "Active": false
}

###
GET http://localhost:4004/odata/v4/pokemon/Teams(124e12d4-d04b-4f19-a26d-ae7c3ec96b16)


###
POST http://localhost:4004/odata/v4/pokemon/Teams
Content-Type: application/json

{
    "Name": "Fail",
    "Active": true
}